//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyG.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyG.Resources.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Быстрый_старт.
        /// </summary>
        public static string HomeView_Title {
            get {
                return ResourceManager.GetString("HomeView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция.
        /// </summary>
        public static string InstructionsView_Title {
            get {
                return ResourceManager.GetString("InstructionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные.
        /// </summary>
        public static string LibrariesView_Title {
            get {
                return ResourceManager.GetString("LibrariesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MainWindow_Controls_SearchWatermark {
            get {
                return ResourceManager.GetString("MainWindow_Controls_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bogza, Bakhlykova @2022.
        /// </summary>
        public static string MainWindow_CreatedByInfo {
            get {
                return ResourceManager.GetString("MainWindow_CreatedByInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyG.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string NewProjectsView_Cancel {
            get {
                return ResourceManager.GetString("NewProjectsView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string NewProjectsView_Ok {
            get {
                return ResourceManager.GetString("NewProjectsView_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа.
        /// </summary>
        public static string NewProjectsView_Program {
            get {
                return ResourceManager.GetString("NewProjectsView_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект.
        /// </summary>
        public static string NewProjectsView_Project {
            get {
                return ResourceManager.GetString("NewProjectsView_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название проекта.
        /// </summary>
        public static string NewProjectsView_Project_Name {
            get {
                return ResourceManager.GetString("NewProjectsView_Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название проекта.
        /// </summary>
        public static string NewProjectsView_Project_ShortName {
            get {
                return ResourceManager.GetString("NewProjectsView_Project_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задание.
        /// </summary>
        public static string NewProjectsView_Task {
            get {
                return ResourceManager.GetString("NewProjectsView_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программы.
        /// </summary>
        public static string ProgramsView_Title {
            get {
                return ResourceManager.GetString("ProgramsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новый проект.
        /// </summary>
        public static string ProjectsView_AddNewProject {
            get {
                return ResourceManager.GetString("ProjectsView_AddNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в PDF.
        /// </summary>
        public static string ProjectsView_ExportPDF {
            get {
                return ResourceManager.GetString("ProjectsView_ExportPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string ProjectsView_Grid_Address {
            get {
                return ResourceManager.GetString("ProjectsView_Grid_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания.
        /// </summary>
        public static string ProjectsView_Grid_Company {
            get {
                return ResourceManager.GetString("ProjectsView_Grid_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создан.
        /// </summary>
        public static string ProjectsView_Grid_Created {
            get {
                return ResourceManager.GetString("ProjectsView_Grid_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата сдачи.
        /// </summary>
        public static string ProjectsView_Grid_Delivery {
            get {
                return ResourceManager.GetString("ProjectsView_Grid_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заметки.
        /// </summary>
        public static string ProjectsView_Grid_Description {
            get {
                return ResourceManager.GetString("ProjectsView_Grid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменен.
        /// </summary>
        public static string ProjectsView_Grid_Edited {
            get {
                return ResourceManager.GetString("ProjectsView_Grid_Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string ProjectsView_Grid_Name {
            get {
                return ResourceManager.GetString("ProjectsView_Grid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        public static string ProjectsView_Grid_Region {
            get {
                return ResourceManager.GetString("ProjectsView_Grid_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название.
        /// </summary>
        public static string ProjectsView_Grid_ShortName {
            get {
                return ResourceManager.GetString("ProjectsView_Grid_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        public static string ProjectsView_Grid_State {
            get {
                return ResourceManager.GetString("ProjectsView_Grid_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        public static string ProjectsView_Print {
            get {
                return ResourceManager.GetString("ProjectsView_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекты.
        /// </summary>
        public static string ProjectsView_Projects {
            get {
                return ResourceManager.GetString("ProjectsView_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск:.
        /// </summary>
        public static string ProjectsView_Search {
            get {
                return ResourceManager.GetString("ProjectsView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать.
        /// </summary>
        public static string ProjectsView_ShowRecordsPart1 {
            get {
                return ResourceManager.GetString("ProjectsView_ShowRecordsPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to записей.
        /// </summary>
        public static string ProjectsView_ShowRecordsPart2 {
            get {
                return ResourceManager.GetString("ProjectsView_ShowRecordsPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекты.
        /// </summary>
        public static string ProjectsView_Title {
            get {
                return ResourceManager.GetString("ProjectsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты_ИГМИ.
        /// </summary>
        public static string ReportsView_Title {
            get {
                return ResourceManager.GetString("ReportsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка_запросов.
        /// </summary>
        public static string RequestsView_Title {
            get {
                return ResourceManager.GetString("RequestsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задания.
        /// </summary>
        public static string TasksView_Tite {
            get {
                return ResourceManager.GetString("TasksView_Tite", resourceCulture);
            }
        }
    }
}
